# Site settings
title: FediGree
email: mail@mabarfuss.de
description: >-
  technical concept paper for distributed genealogy being part of the fediverse.
baseurl: ""
url: "https://decentralizedgenealogy.github.io/ConceptPaper/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  macbarfuss


# Theme settings
footer_content: "Copyright &copy; 2023 DecentralizedGenealogy. Distributed by an <a href=\"https://www.apache.org/licenses/LICENSE-2.0\">Apache 2.0 license.</a>"
color_scheme: dark


# Build settings
theme: just-the-docs
#plugins:
#  - jekyll-plantuml

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
