name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ghcr.io/macbarfuss/sphinxbuilder:main
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v2
      - run: |
          git checkout gh-pages
          git rebase main
          make html
          git commit -I "commit after building sphinx docs"
          git push
